tools:
  verbose: true          # 全局详细输出
  format: plain         # 全局输出格式（改回默认的plain）

  list:
    show_all: true      # 默认显示隐藏文件
    long: true          # 默认显示详细信息

  duplicates:
    recursive: true     # 默认递归扫描
    min_size: 1         # 默认最小文件大小（改为1字节）

  rename:
    dry_run: false      # 默认直接执行

  replace:
    extensions: [.txt, .md]  # 默认只处理这些文件类型

  organize:
    mode: type          # 默认按类型整理

ai:
  enabled: true # 或者 false，根据您的需要设置
  provider: deepseek
  api_key: ${DEEPSEEK_API_KEY}  # 建议从环境变量读取API Key
  model: deepseek-chat
  max_tokens: 1000
  temperature: 0.7
  cache_ttl: 3600 # 缓存时间（秒）

  # 功能开关
  features:
    smart_classify: true
    auto_summarize: true
    content_analysis: true

  # 成本控制
  limits:
    daily_requests: 1000
    monthly_budget: 50  # 人民币
